Book_StoreV10/Models/Order.cs
using Microsoft.AspNetCore.Mvc.ModelBinding;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace CoopApp.Models
{
    public class Order
    {     
        public int OrderID { get; set; }          
        public Kunde Student { get; set; }
        public List<Food> Foods { get; set; }
        public DateTime DateTime { get; set; }
    }
}

Book_StoreV10/Pages/Orders/CheckOut.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using CoopApp.Models;
using CoopApp.Repositories;
using CoopApp.Services;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace CoopApp
{
    public class CheckOutModel : PageModel
    {
       private JsonOrderRepository repository;
        private ShoppingCartService cart;
        
        [BindProperty]
        public Kunde Student { get; set; }   
        public Order Order { get; set; }

        public CheckOutModel(JsonOrderRepository repo, ShoppingCartService cartService)
        {
            repository = repo;
            cart = cartService;
        }
        public void OnGet()
        {
            //Student s = Student;
        }
        public IActionResult OnPost()
        {
            if (!ModelState.IsValid)
            {
                return Page();
            }
            Order order = new Order();
            order.OrderID = 12;
            order.Student = Student;
            order.Foods =  cart.GetOrderedFoods();
            order.DateTime= DateTime.Now ;
            repository.AddOrder(order);
            return RedirectToPage("Order", Student);
        }
    }
}

Book_StoreV10/Pages/Orders/Order.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using CoopApp.Models;
using CoopApp.Repositories;
using CoopApp.Services;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace CoopApp
{
    public class OrderModel : PageModel
    {
        private JsonOrderRepository repository;

        private ShoppingCartService cart;

        public Kunde Student { get; set; }
        public Order Order { get; set; }   
        public List<Food> cartItems { get; set; }

        public OrderModel(JsonOrderRepository repoService, ShoppingCartService cartService)
        {
            repository = repoService;
            cart = cartService;
        }

        public IActionResult OnGet(Kunde st)
        {
            Student = st;              
            cartItems = cart.GetOrderedFoods();
            if (cartItems?.Count() <= 0)
            {
                return Redirect("ShoppingCart");
            }
            return Page();
        }
    }
}

Book_StoreV10/Pages/Orders/ShoppingCart.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using CoopApp.Interfaces;
using CoopApp.Models;
using CoopApp.Services;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace CoopApp
{
    public class ShoppingCartModel : PageModel
    {
        public ShoppingCartService ChartService { get; }
        public List<Food> OrderedFoods { get; set; }
        private IFoodsRepository repo;

        public Food  Food{ get; set; }

        public ShoppingCartModel(IFoodsRepository repository , ShoppingCartService chart)
        {
            repo = repository;
            ChartService = chart;
            OrderedFoods = new List<Food>();
       }
        public IActionResult OnGet(int VareNummer)
        {
            Food food = repo.GetFood(VareNummer);
            ChartService.Add(food);
            OrderedFoods = ChartService.GetOrderedFoods();
            return Page();
        }

         public IActionResult OnPostDelete(int VareNummer)
         {
            ChartService.RemoveFood(VareNummer);
            OrderedFoods = ChartService.GetOrderedFoods();
            return Page();
        }
    }
}

Book_StoreV10/Pages/Orders/CheckOut.cshtml
@page
@model CoopApp.CheckOutModel
@{
    ViewData["Title"] = "CheckOut";
}

<h2 style="glyph-orientation-horizontal">Check-Out</h2>

<form method="post">
    <h3>Please, enter you  information</h3>
    <div class="form-group">
        <label>Id:</label><input asp-for="@Model.Student.Id" class="form-control" />
    </div>
    <div class="form-group">
        <label>Name:</label><input asp-for="@Model.Student.Name" class="form-control" />
    </div>

    <div class="form-group">
        <label>Section:</label><input asp-for="@Model.Student.Section" class="form-control" />
    </div>
    <div class="text-center">
        <input class="btn btn-primary" type="submit" value="Complete Order" />
    </div>
</form>

Book_StoreV10/Pages/Orders/Order.cshtml
@page "{id}"
@model CoopApp.OrderModel
@{
    ViewData["Title"] = "Order";
}

<h4>Hello @Model.Student.Name: Thank you for placing this order on @DateTime.Now</h4>
<h5> Your order contains:</h5>
@foreach (var item in Model.cartItems)
{
    <tr>
        <td class="text-left"> Name: @item.Navn</td>
        <td class="text-right">
            Total Price :
            @((item.Pris).ToString("c"))
        </td>
    </tr>
    <br />
}

<p>We'll ship your items as soon as possible.</p>

Book_StoreV10/Pages/Orders/ShoppingCart.cshtml
@page 
@model CoopApp.ShoppingCartModel
@{
    ViewData["Title"] = "ShoppingCart";
}
<h1>ShoppingCart</h1>
<table class="table table-bordered table-striped">
    <thead>
        <tr>
            <th>Title</th>
            <th>Author</th>
            <th>Image</th>
            <th class="text-right">Price</th>
        </tr>
    </thead>
    @if (Model.OrderedFoods.Count != 0)
    {
        <tbody>
            @foreach (var item in Model.OrderedFoods)
            {
                <tr>
                    <td class="text-center">@item.VareNummer</td>
                    <td class="text-left">@item.Navn</td>
                    <td>
                        <img src="~/Foods/@item.ImageName" width="60" height="70">
                    </td>
                    <td class="text-right">@item.Pris.ToString("c")</td>
                    <td>
                        <form method="post">
                            <button asp-page-handler="Delete" asp-route-isbn="@item.VareNummer"
                                    class="btn btn-danger btn-group-lg pull-right">
                                Delete-From-Chart
                            </button>
                        </form>
                    </td>
                </tr>
            }
        </tbody>
        <tfoot>
            <tr>
                <td colspan="3" class="text-right">Total:</td>
                <td class="text-right">
                    @Model.ChartService.CalculateTotalPrice().ToString("c")
                </td>
            </tr>
        </tfoot>
    }
</table>
<div class="text-center">
    <a asp-page="/Foods/AllFoods" class="btn btn-primary">Continue shopping</a>
    <a asp-page="/Orders/CheckOut" class="btn btn-primary">Check_Out</a>
</div>